---
- hosts: localhost
  tasks:
  - name: install the git latest version
    apt:
     name=git state=latest
  - name: install the docker latest version
    apt:
     name=docker.io state=latest
  - name: install the docker-compose latest version
    apt:
     name=docker-compose state=latest
  - name: install the node  latest version
    apt:
     name=nodejs-legacy state=latest
  - name: install the openssl latest version
    apt:
     name=openssl   state=latest
  - name: Install dependencies
    apt: name="{{item}}"
    with_items:
     - git
     - curl
     - build-essential
     - libssl-dev

  - name: Install nvm
    git: repo=https://github.com/creationix/nvm.git dest=~/.nvm

  - name: Source nvm in ~/.profile
    lineinfile: >
      dest=~/.profile
      line="source ~/.nvm/nvm.sh"
      create=yes
